[package]
name = "cmg-benchmarks"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
cmg = { path = ".." }

[[bin]]
name = "graph-build"
path = "src/bin/graph-build.rs"

[[bin]]
name = "hierarchy-build"
path = "src/bin/hierarchy-build.rs"

[[bin]]
name = "hierarchy-alloc"
path = "src/bin/hierarchy-alloc.rs"

[[bin]]
name = "terminal-build"
path = "src/bin/terminal-build.rs"
